---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-6.4

suites:
  - name: gitlab
    run_list:
      - 'recipe[gitlab-omnibus::default]'
    attributes:
