name             'gitlab-omnibus'
maintainer       'Jeremy Olliver'
maintainer_email 'jeremy.olliver@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures gitlab-omnibus'
long_description 'Installs/Configures gitlab-omnibus'
version          '0.1.0'
